#ifndef GFX_MATERIALCOLOR_H
#define GFX_MATERIALCOLOR_H

#include <nusys.h>

enum {
	MATERIAL_RED = 0,
	MATERIAL_PINK,
	MATERIAL_PURPLE,
	MATERIAL_DEEP_PURPLE,
	MATERIAL_INDIGO,
	MATERIAL_BLUE,
	MATERIAL_LIGHT_BLUE,
	MATERIAL_CYAN,
	MATERIAL_TEAL,
	MATERIAL_GREEN,
	MATERIAL_LIGHT_GREEN,
	MATERIAL_LIME,
	MATERIAL_YELLOW,
	MATERIAL_AMBER,
	MATERIAL_ORANGE,
	MATERIAL_DEEP_ORANGE,
	MATERIAL_BROWN,
	MATERIAL_GREY,
	MATERIAL_DARK_BLUE_GREY,
	MATERIAL_COLOR_COUNT
};

// RGB Color
struct ColorRGB
{
	u8 r;
	u8 g;
	u8 b;
};

// List of colors
extern struct ColorRGB materialColorList[MATERIAL_COLOR_COUNT];

#endif
